import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={inter.className + " h-full"}>
        <div className="flex h-full">
          <div className="w-[17%] pl-3 ">
            <Sidebar />
          </div>
          <div className="w-[83%]">{children}</div>
        </div>
      </body>
    </html>
  );
}
